@startuml
!define LIGHTORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

title Purchase Participation

autonumber
skinparam responseMessageBelowArrow true

actor "HVBank Borrower" as borrower order 1
participant "HVBank" as seller order 3
participant "Ankura Trust" as calculationAgent order 20
participant "WSFS\nTrustee" as trustee order 26
participant "RWA MPT\nTrust" as trust order 25
participant "RWA\n Foundation" as trustSponsor order 30
boundary "Real World/\nDigital World" order 35
participant "Genesis\nTrading" as exchangeBroker order 32
participant "MakerDao" as protocol order 40

group Drawdown of $100mm Dai to Trust Participation Funding Account
  protocol -> protocol : Governance \napproval \nof facility
  protocol -> exchangeBroker : $100mm Dai to broker
  exchangeBroker -> trustSponsor : US$100mm to seller
  trustSponsor -> trustee : escrow US$100mm for \ninvestment and participation purchase 
end

group Trust purchase of particpation
  borrower -> seller : arrange bank loan
  seller -> borrower : loan agreement
  seller -> calculationAgent : HVB requests purchase \nof participation
  calculationAgent -> calculationAgent : participation \ndue diligence
  calculationAgent -> trustee : verifies participation meets criteria
  calculationAgent -> protocol : upload of particpation \nverification info ??
  seller -> trustee : delivery of signed participation
  trustee -> seller : US$xx for pariticpation purchase
end

@enduml
